version: "3"

volumes:
  config:

services:
  app:
    image: makiit/lexoffice-invoice-upload:latest
    volumes:
      - config:/app/config
    environment:
      - TZ=Europe/Berlin
      - INTERVALL=120
    restart: unless-stopped
